# Basic Python

## 1. Split this string

In [ ]:
s = "Hi there Sam!"

In [ ]:
string = "Hi there Sam!"
print(string.split())

['Hi', 'there', 'Sam!']


## 2. Use .format() to print the following string. 

### Output should be: The diameter of Earth is 12742 kilometers.

In [ ]:
planet = "Earth"
diameter = 12742

In [ ]:
planet = "Earth"
diameter = 12742
print( 'The diameter of {} is {} kilometers.' .format(planet,diameter));

The diameter of Earth is 12742 kilometers.


## 3. In this nest dictionary grab the word "hello"

In [ ]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}

In [ ]:
d = {
  'k1': [1, 2, 3, {
    'tricky': ['oh', 'man', 'inception', {
      'target': [1, 2, 3, 'hello']
    }]
  }]
}

# Numpy

In [ ]:
import numpy as np

## 4.1 Create an array of 10 zeros? 
## 4.2 Create an array of 10 fives?

In [ ]:
import numpy as np
array=np.zeros(10)
print("An array of 10 zeros:")
print(array)


An array of 10 zeros:
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [ ]:
array=np.ones(10)*5
print("An array of 10 fives:")
print(array)

An array of 10 fives:
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


## 5. Create an array of all the even integers from 20 to 35

In [ ]:
import numpy as np
array=np.arange(20,36,2)
print("Array of all the even integers from 20 to 35")
print(array) 

Array of all the even integers from 20 to 35
[20 22 24 26 28 30 32 34]


## 6. Create a 3x3 matrix with values ranging from 0 to 8

In [ ]:
import numpy as np
x =  np.arange(0, 9).reshape(3,3)
print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


## 7. Concatenate a and b 
## a = np.array([1, 2, 3]), b = np.array([4, 5, 6])

In [ ]:
import numpy as np
a = np.array([[1, 2, 3]])
b = np.array([[4, 5, 6]])
np.concatenate((a, b))

array([[1, 2, 3],
       [4, 5, 6]])

# Pandas

## 8. Create a dataframe with 3 rows and 2 columns

In [ ]:
import pandas as pd


In [ ]:
# Import pandas library
import pandas as pd

# initialize list of lists
data = [['tom', 10], ['nick', 15]]

# Create the pandas DataFrame
df = pd.DataFrame(data, columns=['Name', 'Age'])

# print dataframe.
df


Name  Age
0   tom   10
1  nick   15

## 9. Generate the series of dates from 1st Jan, 2023 to 10th Feb, 2023

In [ ]:
# importing pandas as pd
import pandas as pd

per1 = pd.date_range(start ='1-1-2023',
		end ='10-02-2023', freq ='6H')

for val in per1:
	print(val)


2023-01-01 00:00:00
2023-01-01 06:00:00
2023-01-01 12:00:00
2023-01-01 18:00:00
2023-01-02 00:00:00
2023-01-02 06:00:00
2023-01-02 12:00:00
2023-01-02 18:00:00
2023-01-03 00:00:00
2023-01-03 06:00:00
2023-01-03 12:00:00
2023-01-03 18:00:00
2023-01-04 00:00:00
2023-01-04 06:00:00
2023-01-04 12:00:00
2023-01-04 18:00:00
2023-01-05 00:00:00
2023-01-05 06:00:00
2023-01-05 12:00:00
2023-01-05 18:00:00
2023-01-06 00:00:00
2023-01-06 06:00:00
2023-01-06 12:00:00
2023-01-06 18:00:00
2023-01-07 00:00:00
2023-01-07 06:00:00
2023-01-07 12:00:00
2023-01-07 18:00:00
2023-01-08 00:00:00
2023-01-08 06:00:00
2023-01-08 12:00:00
2023-01-08 18:00:00
2023-01-09 00:00:00
2023-01-09 06:00:00
2023-01-09 12:00:00
2023-01-09 18:00:00
2023-01-10 00:00:00
2023-01-10 06:00:00
2023-01-10 12:00:00
2023-01-10 18:00:00
2023-01-11 00:00:00
2023-01-11 06:00:00
2023-01-11 12:00:00
2023-01-11 18:00:00
2023-01-12 00:00:00
2023-01-12 06:00:00
2023-01-12 12:00:00
2023-01-12 18:00:00
2023-01-13 00:00:00
2023-01-13 06:00:00


## 10. Create 2D list to DataFrame

lists = [[1, 'aaa', 22],
         [2, 'bbb', 25],
         [3, 'ccc', 24]]

In [ ]:
lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]

In [ ]:
# Import pandas library
import pandas as pd

# initialize list of lists
data = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24] ]

# Create the pandas DataFrame
df = pd.DataFrame(data, columns = ['Category', 'Name', 'Marks'])

# print dataframe.
print(df )


   Category Name  Marks
0         1  aaa     22
1         2  bbb     25
2         3  ccc     24
